
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frbptbubfqdknmjgdlsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYnB0YnViZnFka25tamdkbHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTIzNjQsImV4cCI6MjA2MDQ4ODM2NH0.fpeSHCwUHy-T1DeGD-feTbhsKrad9s3vZ58yIUBtna4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
